inherit_from:
  - .rubocop_airbnb.yml

# Rails用に最適化
Rails:
  Enabled: true

#Rubocopで検証したくないフォルダ/ファイルを指定
AllCops:
  Exclude:
    - 'bin/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seed.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
